name: courseflutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.3.0
  # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.8
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.5.1
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 0.3.18+1
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.0.0-rc
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.3
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: 0.2.6+1
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^4.0.2
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.5
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/splash/
    - assets/data/
    - assets/images/


  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf


